[2025-03-17T22:32:14.450+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.load_phase_task manual__2025-03-16T15:28:09.434150+00:00 [queued]>
[2025-03-17T22:32:14.640+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.load_phase_task manual__2025-03-16T15:28:09.434150+00:00 [queued]>
[2025-03-17T22:32:14.641+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-17T22:32:14.962+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_phase_task> on 2025-03-16 15:28:09.434150+00:00
[2025-03-17T22:32:14.977+0000] {standard_task_runner.py:60} INFO - Started process 17648 to run task
[2025-03-17T22:32:14.996+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'load_phase_task', 'manual__2025-03-16T15:28:09.434150+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmpmle7t460']
[2025-03-17T22:32:15.020+0000] {standard_task_runner.py:88} INFO - Job 210: Subtask load_phase_task
[2025-03-17T22:32:15.367+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.load_phase_task manual__2025-03-16T15:28:09.434150+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-17T22:32:16.369+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='load_phase_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T15:28:09.434150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T15:28:09.434150+00:00'
[2025-03-17T22:32:16.373+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-17T22:32:16.375+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ~/data_warehouse_project && dbt run --profiles-dir ~/.dbt --models dim_bank dim_branch dim_location dim_sentiment fact_reviews']
[2025-03-17T22:32:16.413+0000] {subprocess.py:86} INFO - Output:
[2025-03-17T22:32:31.078+0000] {subprocess.py:93} INFO - [0m22:32:31  Running with dbt=1.9.0-b2
[2025-03-17T22:32:34.227+0000] {subprocess.py:93} INFO - [0m22:32:34  Registered adapter: postgres=1.8.2
[2025-03-17T22:32:36.737+0000] {subprocess.py:93} INFO - [0m22:32:36  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-17T22:32:36.738+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-17T22:32:36.738+0000] {subprocess.py:93} INFO - - models.data_warehouse_project.example
[2025-03-17T22:32:38.226+0000] {subprocess.py:93} INFO - [0m22:32:38  Found 6 models, 1 source, 424 macros
[2025-03-17T22:32:38.251+0000] {subprocess.py:93} INFO - [0m22:32:38
[2025-03-17T22:32:38.254+0000] {subprocess.py:93} INFO - [0m22:32:38  Concurrency: 4 threads (target='dev')
[2025-03-17T22:32:38.255+0000] {subprocess.py:93} INFO - [0m22:32:38
[2025-03-17T22:32:39.246+0000] {subprocess.py:93} INFO - [0m22:32:39  1 of 5 START sql table model public_Decisionnelle.dim_bank ..................... [RUN]
[2025-03-17T22:32:39.276+0000] {subprocess.py:93} INFO - [0m22:32:39  2 of 5 START sql table model public_Decisionnelle.dim_branch ................... [RUN]
[2025-03-17T22:32:39.289+0000] {subprocess.py:93} INFO - [0m22:32:39  3 of 5 START sql table model public_Decisionnelle.dim_location ................. [RUN]
[2025-03-17T22:32:39.295+0000] {subprocess.py:93} INFO - [0m22:32:39  4 of 5 START sql table model public_Decisionnelle.dim_sentiment ................ [RUN]
[2025-03-17T22:32:40.995+0000] {subprocess.py:93} INFO - [0m22:32:40  2 of 5 OK created sql table model public_Decisionnelle.dim_branch .............. [[32mSELECT 2[0m in 1.68s]
[2025-03-17T22:32:41.030+0000] {subprocess.py:93} INFO - [0m22:32:41  1 of 5 OK created sql table model public_Decisionnelle.dim_bank ................ [[32mSELECT 2[0m in 1.78s]
[2025-03-17T22:32:41.044+0000] {subprocess.py:93} INFO - [0m22:32:41  4 of 5 OK created sql table model public_Decisionnelle.dim_sentiment ........... [[32mSELECT 1[0m in 1.68s]
[2025-03-17T22:32:41.054+0000] {subprocess.py:93} INFO - [0m22:32:41  3 of 5 OK created sql table model public_Decisionnelle.dim_location ............ [[32mSELECT 2[0m in 1.74s]
[2025-03-17T22:32:41.064+0000] {subprocess.py:93} INFO - [0m22:32:41  5 of 5 START sql table model public_Decisionnelle.fact_reviews ................. [RUN]
[2025-03-17T22:32:41.423+0000] {subprocess.py:93} INFO - [0m22:32:41  5 of 5 OK created sql table model public_Decisionnelle.fact_reviews ............ [[32mSELECT 0[0m in 0.36s]
[2025-03-17T22:32:41.535+0000] {subprocess.py:93} INFO - [0m22:32:41
[2025-03-17T22:32:41.537+0000] {subprocess.py:93} INFO - [0m22:32:41  Finished running 5 table models in 0 hours 0 minutes and 3.28 seconds (3.28s).
[2025-03-17T22:32:41.734+0000] {subprocess.py:93} INFO - [0m22:32:41
[2025-03-17T22:32:41.736+0000] {subprocess.py:93} INFO - [0m22:32:41  [32mCompleted successfully[0m
[2025-03-17T22:32:41.737+0000] {subprocess.py:93} INFO - [0m22:32:41
[2025-03-17T22:32:41.738+0000] {subprocess.py:93} INFO - [0m22:32:41  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5
[2025-03-17T22:32:44.463+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-17T22:32:44.737+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Google_map, task_id=load_phase_task, execution_date=20250316T152809, start_date=20250317T223214, end_date=20250317T223244
[2025-03-17T22:32:44.842+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-17T22:32:45.001+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
