[2025-03-17T11:45:16.765+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.transform_data_phase_1_task manual__2025-03-17T11:45:10.561715+00:00 [queued]>
[2025-03-17T11:45:16.819+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.transform_data_phase_1_task manual__2025-03-17T11:45:10.561715+00:00 [queued]>
[2025-03-17T11:45:16.820+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-17T11:45:16.924+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): transform_data_phase_1_task> on 2025-03-17 11:45:10.561715+00:00
[2025-03-17T11:45:16.948+0000] {standard_task_runner.py:60} INFO - Started process 25153 to run task
[2025-03-17T11:45:16.963+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'transform_data_phase_1_task', 'manual__2025-03-17T11:45:10.561715+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmpaboqz9_p']
[2025-03-17T11:45:16.971+0000] {standard_task_runner.py:88} INFO - Job 154: Subtask transform_data_phase_1_task
[2025-03-17T11:45:17.348+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.transform_data_phase_1_task manual__2025-03-17T11:45:10.561715+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-17T11:45:18.133+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='transform_data_phase_1_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T11:45:10.561715+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T11:45:10.561715+00:00'
[2025-03-17T11:45:18.136+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-17T11:45:18.151+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ~/data_warehouse_project && dbt run --profiles-dir ~/.dbt --models cleaned_reviews']
[2025-03-17T11:45:18.275+0000] {subprocess.py:86} INFO - Output:
[2025-03-17T11:45:24.968+0000] {subprocess.py:93} INFO - [0m11:45:24  Running with dbt=1.9.0-b2
[2025-03-17T11:45:25.774+0000] {subprocess.py:93} INFO - [0m11:45:25  Registered adapter: postgres=1.8.2
[2025-03-17T11:45:26.687+0000] {subprocess.py:93} INFO - [0m11:45:26  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-17T11:45:26.688+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-17T11:45:26.689+0000] {subprocess.py:93} INFO - - models.data_warehouse_project.example
[2025-03-17T11:45:27.257+0000] {subprocess.py:93} INFO - [0m11:45:27  Found 1 model, 1 source, 424 macros
[2025-03-17T11:45:27.262+0000] {subprocess.py:93} INFO - [0m11:45:27
[2025-03-17T11:45:27.263+0000] {subprocess.py:93} INFO - [0m11:45:27  Concurrency: 4 threads (target='dev')
[2025-03-17T11:45:27.265+0000] {subprocess.py:93} INFO - [0m11:45:27
[2025-03-17T11:45:27.684+0000] {subprocess.py:93} INFO - [0m11:45:27  1 of 1 START sql table model public.cleaned_reviews ............................ [RUN]
[2025-03-17T11:45:28.229+0000] {subprocess.py:93} INFO - [0m11:45:28  1 of 1 OK created sql table model public.cleaned_reviews ....................... [[32mSELECT 9[0m in 0.54s]
[2025-03-17T11:45:28.264+0000] {subprocess.py:93} INFO - [0m11:45:28
[2025-03-17T11:45:28.266+0000] {subprocess.py:93} INFO - [0m11:45:28  Finished running 1 table model in 0 hours 0 minutes and 1.00 seconds (1.00s).
[2025-03-17T11:45:28.348+0000] {subprocess.py:93} INFO - [0m11:45:28
[2025-03-17T11:45:28.351+0000] {subprocess.py:93} INFO - [0m11:45:28  [32mCompleted successfully[0m
[2025-03-17T11:45:28.353+0000] {subprocess.py:93} INFO - [0m11:45:28
[2025-03-17T11:45:28.354+0000] {subprocess.py:93} INFO - [0m11:45:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-17T11:45:30.239+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-17T11:45:30.354+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Google_map, task_id=transform_data_phase_1_task, execution_date=20250317T114510, start_date=20250317T114516, end_date=20250317T114530
[2025-03-17T11:45:30.422+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-17T11:45:30.486+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
