[2025-03-17T22:35:11.976+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_map.load_phase_task manual__2025-03-17T22:29:46.221740+00:00 [queued]>
[2025-03-17T22:35:12.004+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_map.load_phase_task manual__2025-03-17T22:29:46.221740+00:00 [queued]>
[2025-03-17T22:35:12.005+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-03-17T22:35:12.043+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_phase_task> on 2025-03-17 22:29:46.221740+00:00
[2025-03-17T22:35:12.049+0000] {standard_task_runner.py:60} INFO - Started process 20336 to run task
[2025-03-17T22:35:12.062+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'Google_map', 'load_phase_task', 'manual__2025-03-17T22:29:46.221740+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/google_map_dag_etl.py', '--cfg-path', '/tmp/tmpz20uxmbg']
[2025-03-17T22:35:12.065+0000] {standard_task_runner.py:88} INFO - Job 229: Subtask load_phase_task
[2025-03-17T22:35:12.318+0000] {task_command.py:423} INFO - Running <TaskInstance: Google_map.load_phase_task manual__2025-03-17T22:29:46.221740+00:00 [running]> on host DESKTOP-AVAHALM.
[2025-03-17T22:35:12.714+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='master_m2si' AIRFLOW_CTX_DAG_ID='Google_map' AIRFLOW_CTX_TASK_ID='load_phase_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T22:29:46.221740+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T22:29:46.221740+00:00'
[2025-03-17T22:35:12.719+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-17T22:35:12.722+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd ~/data_warehouse_project && dbt run --profiles-dir ~/.dbt --models dim_bank dim_branch dim_location dim_sentiment fact_reviews']
[2025-03-17T22:35:12.753+0000] {subprocess.py:86} INFO - Output:
[2025-03-17T22:35:16.358+0000] {subprocess.py:93} INFO - [0m22:35:16  Running with dbt=1.9.0-b2
[2025-03-17T22:35:16.914+0000] {subprocess.py:93} INFO - [0m22:35:16  Registered adapter: postgres=1.8.2
[2025-03-17T22:35:17.759+0000] {subprocess.py:93} INFO - [0m22:35:17  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-17T22:35:17.759+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-17T22:35:17.759+0000] {subprocess.py:93} INFO - - models.data_warehouse_project.example
[2025-03-17T22:35:18.298+0000] {subprocess.py:93} INFO - [0m22:35:18  Found 6 models, 1 source, 424 macros
[2025-03-17T22:35:18.305+0000] {subprocess.py:93} INFO - [0m22:35:18
[2025-03-17T22:35:18.313+0000] {subprocess.py:93} INFO - [0m22:35:18  Concurrency: 4 threads (target='dev')
[2025-03-17T22:35:18.318+0000] {subprocess.py:93} INFO - [0m22:35:18
[2025-03-17T22:35:18.844+0000] {subprocess.py:93} INFO - [0m22:35:18  1 of 5 START sql table model public_Decisionnelle.dim_bank ..................... [RUN]
[2025-03-17T22:35:18.849+0000] {subprocess.py:93} INFO - [0m22:35:18  2 of 5 START sql table model public_Decisionnelle.dim_branch ................... [RUN]
[2025-03-17T22:35:18.887+0000] {subprocess.py:93} INFO - [0m22:35:18  3 of 5 START sql table model public_Decisionnelle.dim_location ................. [RUN]
[2025-03-17T22:35:18.896+0000] {subprocess.py:93} INFO - [0m22:35:18  4 of 5 START sql table model public_Decisionnelle.dim_sentiment ................ [RUN]
[2025-03-17T22:35:19.835+0000] {subprocess.py:93} INFO - [0m22:35:19  3 of 5 OK created sql table model public_Decisionnelle.dim_location ............ [[32mSELECT 2[0m in 0.93s]
[2025-03-17T22:35:19.851+0000] {subprocess.py:93} INFO - [0m22:35:19  1 of 5 OK created sql table model public_Decisionnelle.dim_bank ................ [[32mSELECT 2[0m in 0.99s]
[2025-03-17T22:35:19.857+0000] {subprocess.py:93} INFO - [0m22:35:19  4 of 5 OK created sql table model public_Decisionnelle.dim_sentiment ........... [[32mSELECT 1[0m in 0.94s]
[2025-03-17T22:35:19.870+0000] {subprocess.py:93} INFO - [0m22:35:19  2 of 5 OK created sql table model public_Decisionnelle.dim_branch .............. [[32mSELECT 2[0m in 1.02s]
[2025-03-17T22:35:19.878+0000] {subprocess.py:93} INFO - [0m22:35:19  5 of 5 START sql table model public_Decisionnelle.fact_reviews ................. [RUN]
[2025-03-17T22:35:20.014+0000] {subprocess.py:93} INFO - [0m22:35:20  5 of 5 OK created sql table model public_Decisionnelle.fact_reviews ............ [[32mSELECT 0[0m in 0.13s]
[2025-03-17T22:35:20.044+0000] {subprocess.py:93} INFO - [0m22:35:20
[2025-03-17T22:35:20.044+0000] {subprocess.py:93} INFO - [0m22:35:20  Finished running 5 table models in 0 hours 0 minutes and 1.72 seconds (1.72s).
[2025-03-17T22:35:20.107+0000] {subprocess.py:93} INFO - [0m22:35:20
[2025-03-17T22:35:20.110+0000] {subprocess.py:93} INFO - [0m22:35:20  [32mCompleted successfully[0m
[2025-03-17T22:35:20.111+0000] {subprocess.py:93} INFO - [0m22:35:20
[2025-03-17T22:35:20.113+0000] {subprocess.py:93} INFO - [0m22:35:20  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5
[2025-03-17T22:35:22.033+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-17T22:35:22.105+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Google_map, task_id=load_phase_task, execution_date=20250317T222946, start_date=20250317T223511, end_date=20250317T223522
[2025-03-17T22:35:22.158+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-17T22:35:22.196+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
